apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dfmweb
  namespace: dfmweb
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
spec:
  ingressClassName: nginx
  rules:
    - host: dfmweb.example.local  # TODO: 替换为实际域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dfmweb
                port:
                  number: 80