apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dfmweb
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: dfmweb
  app.kubernetes.io/part-of: stellantis-overseas-tsp