apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msrcs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dfm
  source:
    repoURL: https://github.com/zxc-dev/dfmweb-gitops.git
    targetRevision: k8s_sit_test
    path: charts/msrcs
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: msrcs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m